version: '2'

services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    command: 'start-dev --import-realm'

volumes:
  mongodb_data:
    driver: local
