version: '2'

services:
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/db
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    command: 'start-dev --import-realm'

volumes:
  db_data:
    driver: local
