version: "3.3"
services:
  app:
    image: event
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env-dev
    environment:
      - MONGO_HOST=db
  db:
    image: mongo:5.0.5
    restart: always
