version: "3.3"
services:
  app:
    image: event
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - keycloak
    env_file:
      - .env-dev
    environment:
      - DB_HOST=db
      - KEYCLOAK_URL=http://keycloak:9090
  db:
    image: postgres:17.0
    restart: always
    volumes:
      - db_data:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    command: 'start-dev --import-realm'

volumes:
  db_data:
    driver: local
