# Custom keys
fi.asteriski.config.event.root-path-bannerimg=/tmp/
fi.asteriski.config.security.allowed-cors-domain=http://localhost:3000

# DB config
spring.jpa.show-sql=true
# Remove H2 config before merging into develop
spring.datasource.url=jdbc:h2:mem:eventsignup;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

# OpenApi
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=false
