FROM quay.io/keycloak/keycloak:23.0.4

COPY realm/asteriski-realm.json /opt/keycloak/data/import/asteriski-realm.json
COPY themes/asteriski /opt/keycloak/themes

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm"]
