/*
Copyright Juhani Vähä-Mäkilä (juhani@fmail.co.uk) 2022.
Licenced under EUROPEAN UNION PUBLIC LICENCE v. 1.2.
 */
package fi.asteriski.eventsignup.model.event;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import java.util.Map;
import javax.validation.constraints.NotNull;
import lombok.Data;

@Data
public class Form {

    /*
    NOTE!
    Fields must not have @NonNull annotation.
    Otherwise, conversion from incoming json to EventDto in EventController will fail!
     */
    private Instant dateCreated;

    @NotNull
    @Schema(description = "generated by formGenerator")
    private Map<String, Object> formData;

    private String userCreated;
}
