name: Build and publish a Docker image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'develop'
jobs:
  eventsignup_backend-image:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        if: ${{ github.ref_type == 'tag' }}
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  typescript-types:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21
    env:
      MONGO_HOST: localhost
      KEYCLOAK_URL: localhost
    steps:
      - uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '5.0.5'

      - name: Authenticate to github packages
        run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.gh_token }}' > ~/.npmrc

      - name: Update typescript types
        run: ./gradlew generateTsTypes

      - name: Generate new version number
        run: ./gradlew generateTypesVersionNumber

      - name: Push new version to npm registry
        run: ./gradlew publishTypesPlugin

  keycloak-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}

      - name: Build keycloak image
        run: docker build --file keycloak/Dockerfile.ci --tag ghcr.io/asteriskiry/keycloak:latest keycloak

      - name: Push keycloak image to container registry
        run: docker push ghcr.io/asteriskiry/keycloak:latest
