name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container:
      image: openjdk:21
    env:
      MONGO_HOST: localhost

    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests
        run: ./gradlew check

      - name: Tests that app builds
        run: ./gradlew bootJar
