name: Docker Image CI

on:
  push:
    branches: [ "develop", "feature/keycloak" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}

      - name: Build server image
        run: docker build . --file Dockerfile --tag eventsignup_backend:latest

      - name: Push server image to container registry
        run: docker push ghcr.io/asteriskiry/eventsignup_backend:latest
