name: Update artifacts

on:
  push:
    branches: [ "develop", "feature/keycloak" ]
  workflow_dispatch:

jobs:
  eventsignup_backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}

      - name: Build image
        run: docker build --file Dockerfile --tag ghcr.io/asteriskiry/eventsignup_backend:latest .

      - name: Push image to container registry
        run: docker push ghcr.io/asteriskiry/eventsignup_backend:latest

  keycloak-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}

      - name: Build keycloak image
        run: docker build --file keycloak/Dockerfile.ci --tag ghcr.io/asteriskiry/keycloak:latest keycloak

      - name: Push keycloak image to container registry
        run: docker push ghcr.io/asteriskiry/keycloak:latest


  typescript-types:
    runs-on: ubuntu-latest
    container: openjdk:21
    env:
      MONGO_HOST: mongo
      KEYCLOAK_URL: localhost
    services:
      mongo:
        image: mongo:5.0.5
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to github packages
        run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.gh_token }}' > ~/.npmrc

      - name: Update typescript types
        run: ./gradlew generateTsTypes

      - name: Generate new version number
        run: ./gradlew generateTypesVersionNumber

      - name: Push new version to npm registry
        run: ./gradlew publishTypesPlugin
